lzc-sdk-version: "0.1"
name: Forgejo
package: cloud.lazycat.app.forgejo
version: 10.0.1
min_os_version: 1.3.0
description: Gitea 的一个硬分叉版本
homepage: https://forgejo.org
author: forgejo
application:
  subdomain: fogejo
  background_task: true
  multi_instance: false
  gpu_accel: false
  kvm_accel: false
  usb_accel: false
  routes:
    - /=http://forgejo-server.cloud.lazycat.app.forgejo.lzcapp:3000/
  public_path:
    - /
  ingress:
    - protocol: tcp
      port: 22
      service: forgejo-server
services:
  forgejo-server:
    image: registry.lazycat.cloud/czyt/forgejo/forgejo:fa539141b967a89d
    environment:
      - USER_UID=1000
      - USER_GID=1000
    binds:
      - /lzcapp/var/data:/data
